export const SPAIN_PRIZE_IDS = {
  GIRL_POWER_PRIMERA: 4,
  GIRL_POWER_SEGUNDA: 5,
  MARTIN_LEAGUE: 6,
  SOFT_KITTY: 19,
  CLASSIC: 22,
  SPICY_PEPE: 23,
  TURTLE_HUNT: 24,
  HANDY_HANDS: 25,
  MARTIN_POINTS: 26,
  FIRE_MATCH: 27,
  FIRST_HUNDRED: 28,
  LEGENDARY_SEVEN: 29,
} as const;
